### ISSUE TITLE
Integration Testing Drag and Drop

### ISSUE THREAD

**Issue by bentrility** [Gavant/ember-shopify-draggable#10]
Thanks for your work on this. Any chance you can add some examples of testing the drag and drop functionality? For example, 

Given a list of 2 elements, 
When I drag the first element to the second spot, 
then the list is reordered 
and the appropriate events fire.

**Comment by billdami** [comment]
Hi @bentrility, thanks for your feedback! Take a look at the integration test added in PR #11 and let us know if that is what you're looking for. That test drags an element to a new spot, and then verifies that the DOM has updated, and that the underlying list array was updated (i.e. the `itemReordered` event was fired).

**Comment by bentrility** [comment]
Thank you for doing this. Pulling it down and taking a look this morning!
